### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/S6070_r.csv'

### ISSUE THREAD

**Issue by JinyuanSun** [ZhiweiNiepku/S3C#1]
FileNotFoundError: [Errno 2] No such file or directory: 'data/S6070_r.csv'

**Comment by Ma-Yiming** [comment]
> FileNotFoundError: [Errno 2] No such file or directory: 'data/S6070_r.csv'

Thank you for the question!!! we've fixed it.
